### ISSUE TITLE
Missing error handler on `socket`. TypeError: (msg || "").replace is not a function Error

### ISSUE THREAD

**Issue by whelanp** [karma-runner/karma#1969]
I'm getting the above error when I try to run jenkins jobs using karma. Any ideas what could be causing this?

### Expected behavior

karma runs angular2 tests on jenkins, they run fine on desktop.

### Actual behavior

```
`Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function
    at /home/hudson/.hudson/jobs/workspace/example/node_modules/karma/lib/reporter.js:45:23
    at onBrowserError (/home/hudson/.hudson/jobs/workspace/example/node_modules/karma/lib/reporters/base.js:58:60)
    at null.<anonymous> (/home/hudson/.hudson/jobs/workspace/example/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at onKarmaError (/home/hudson/.hudson/jobs/workspace/example/node_modules/karma/lib/browser.js:95:13)
    at Socket.<anonymous> (/home/hudson/.hudson/jobs/workspace/example/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (/home/hudson/.hudson/jobs/workspace/example/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/hudson/.hudson/jobs/workspace/example/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/hudson/.hudson/jobs/workspace/example/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/hudson/.hudson/jobs/workspace/example/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/hudson/.hudson/jobs/workspace/example/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/hudson/.hudson/jobs/workspace/example/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:90:13)`
```

### Enviroment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

+ node --version
v5.7.0
+ npm --version
3.6.0
karma version
0.13.21

### Steps to reproduce the behaviour

1. run tests in jenkins, (independent of the tests running) the above stacktrace is displayed

**Comment by whelanp** [comment]
Just giving an update on this issue, I eventually got console access to the build server and found the root cause of this issue.

In my files section I had the following entry

`{ pattern: 'node_modules/rxjs/bundles/rx.js', included: true, watched: true }
`

The file name is actually **Rx.js** and not **rx.js**, this was not a problem with case insensitive windows. Fixing the filename case and everything is now consistent.

`{ pattern: 'node_modules/rxjs/bundles/Rx.js', included: true, watched: true }
`

I appreciate any time anyone spent on this issue till now. Turns out the exception I focused in on was a symptom of the file not being found.  

Thanks
Paul

**Comment by dignifiedquire** [comment]
Thanks for the update, and happy to hear you were able to fix it.

**Comment by tlefevre** [comment]
@dignifiedquire there's still a problem to be fixed and that is the error message. It is very unhelpful and it would be very much appreciated by the community, I'm guessing, if the quality of that was improved. As shown here, the problem was a missing file. A missing file error would be much more appropriate and helpful to users.

**Comment by klinki** [comment]
I have the same problem, but I already have Rx.js file with capital R. (And I'm using my desktop computer with Windows).

What else could cause for this problem?

**Comment by JohnMunsch** [comment]
I can answer that question: traceur-runtime.js

Or rather, the lack of it. For some bizarre reason, without the traceur-runtime.js in the mix PhantomJS blows up badly while trying to run Angular2 unit tests. This doesn't seem to be a Karma thing at all, but I thought I'd mention it here so some people could fix their problem. I installed it via bower ("bower install traceur-runtime") and included it in my karma.conf.js ("{pattern: 'bower_components/traceur-runtime/traceur-runtime.js', included: true, watched: true}") and magically PhantomJS suddenly worked just as well as Chrome had.

**Comment by JoostvdB94** [comment]
I had this problem a few times. I managed to fix this by checking the `files: []` section in the `karma.conf.js`. Make sure all the sources that are needed for your application (in my case Angular2) are in that array. Just as you would add them to index.html

**Comment by Cuel** [comment]
>I can answer that question: traceur-runtime.js
Or rather, the lack of it. For some bizarre reason, without the traceur-runtime.js in the mix PhantomJS blows up badly while trying to run Angular2 unit tests. This doesn't seem to be a Karma thing at all, but I thought I'd mention it here so some people could fix their problem. I installed it via bower ("bower install traceur-runtime") and included it in my karma.conf.js ("{pattern: 'bower_components/traceur-runtime/traceur-runtime.js', included: true, watched: true}") and magically PhantomJS suddenly worked just as well as Chrome had.

@JohnMunsch shouldn't es6-shim make up for that? I'm also just getting "module is not defined" if I include it in the karma.conf.js files

**Comment by yfain** [comment]
I'm getting this error if I run my Karma tests from the console opened inside WebStorm IDE. The same configuration runs fine from the Terminal window on my Mac OS.

**Comment by JohnMunsch** [comment]
@Cuel I agree, you would think that es6-shim would cover everything. But I'm not the first to find that traceur-runtime had to be added back to the mix in order for PhantomJS to work.

**Comment by dignifiedquire** [comment]
If you don't want to use traceur-runtime you could try [core.js](https://github.com/zloirock/core-js) which karma uses itself.

**Comment by drew-moore** [comment]
@yfain same story here, but on Windows with IntelliJ: I get this error when I try to run the command from IntelliJ console, but it runs just fine when executed from Powershell. I'm opening a ticket with Jetbrains now,

**Comment by shaikhspear16** [comment]
I get this error when i add 'browserify' to preprocessors.
```

 preprocessors: {
            'unit-test/linkers/**/!(*spec).js': ['coverage','browserify']
        }
```

I was getting require not found when running karma, that made me add browserify, now i get this error.

**Comment by gabor-farkas** [comment]
I think this is really a bug somewhere, though I'm not sure where.
The actual excepion occurs because the karma reporter assumes that only strings come as error messages from the browser, but that's apparently not the case.
You can just open up node_modules/karma/lib/reporter.js and change the method around line 42:
```javascript
  return function (msg, indentation) {
    // remove domain and timestamp from source files
    // and resolve base path / absolute path urls into absolute path
    // ---
    if (msg && typeof(msg) !== 'string') {
      console.error('msg', msg);
    }
    // ---
    msg = (msg || '').replace(URL_REGEXP, function (_, prefix, path, __, ___, line, ____, column) {
```

For my particular case it tells me that some error occured in SystemJS, though I doesn't tell more.

The actual fix would be either not to assume here that msg is a string, or maybe the browsers should send objects as error messages.

**Comment by randyaa** [comment]
i fixed this locally by adding the following lines to `karma/lib/reporter.js` @ line 45:

```
      if ( typeof msg !== "string") {
          msg = JSON.stringify(msg);
      }
``` 

so at least there's output

**Comment by nonmanifold** [comment]
https://youtrack.jetbrains.com/issue/WEB-23485?query=intellijUtil.js filed a bug to JetBrains

**Comment by dileepkeeppalli** [comment]
I am still facing this issue with node-forge.

`404: /base/node_modules/node-forge/js/node-forge.js
Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function
    at /GE/ROBUSTA_APP/robusta-core/node_modules/karma/lib/reporter.js:45:23`

**Comment by nonmanifold** [comment]
thats probably because msg became an array of strings, I'll look up into it later today

**Comment by dileepkeeppalli** [comment]
@nonmanifold Issue has fixed for me

**Comment by saranyapm** [comment]
I am also getting the same issue..Tried many options but everything failed :( :(

**Comment by dileepkeeppalli** [comment]
@saranyapm Hey
Did you add any new node module and that dependency in any of your angular2 application component?
If so you have to set the path in `system.config.js` and `karma.config.js` then probably you will come out from this issue. 
Sample code
system.config.js
`'node-xyz': 'node_modules/node-xyz/xyz'

karma.config.js
`{pattern: 'node_modules/node-xyz/xyz.js', included: false, watched: false},`

please try this

**Comment by saranyapm** [comment]
@dileepkeeppalli  No..No such module. Now I am trying only with app component. Still I am facing the same issue.
