### ISSUE TITLE
Make console.log to be logged rather then reported ?

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#480]
Based on #419 I think we might provide this feature - allow redirecting `console.log` to a file.

**Comment by aselivanov** [comment]
+1

**Comment by n-h** [comment]
+1

**Comment by baer** [comment]
+1

**Comment by michaelmalone** [comment]
+1

**Comment by Stratus3D** [comment]
+1

**Comment by mjuniper** [comment]
:+1:

**Comment by PavelKonon** [comment]
:+1:

**Comment by charliecm** [comment]
:+1:

**Comment by maffelbaffel** [comment]
+1

**Comment by jsnbuchanan** [comment]
+1

**Comment by vladimirvolek** [comment]
+1

**Comment by kevzettler** [comment]
+1

**Comment by jonahx** [comment]
+1

**Comment by jonahx** [comment]
For those looking for a quick and dirty fix for now, putting the following line:

    console.log = function() {}

at the top of your spec file will suppress all console.log statements in your code, for obvious reasons.

**Comment by nelsonomuto** [comment]
+1

**Comment by jnikles** [comment]
+1

**Comment by GrimDev** [comment]
+1

**Comment by gregor** [comment]
+1

**Comment by alexpop89** [comment]
+1

**Comment by budde377** [comment]
I'm going to attempt to implement this as soon as my outstanding pull-requests has been resolved.

**Comment by aug-riedinger** [comment]
I don't understand how this is supposed to work:

I'd expect that in my code, if I have:

```
console.info('info logging');
console.debug('debug logging');
```

Then when I have `logLevel: config.LOG_INFO`, I'll read the `info logging` one, while if I have `logLevel: config.LOG_DEBUG`, I'll read both `info logging` and `debug logging`.

Am I correct? Did I miss something?

Thanks

**Comment by Macadoshis** [comment]
2019, karma version "^2.0.5" and yet this is still not working... :unamused:

`logLevel: config.LOG_DEBUG` and all my `console.debug(..)`are still b eing displayed in standard output....

**Comment by johnjbarton** [comment]
`logLevel` operates on the karma server. `console.debug()` operates in the browser.  The browser logging flows through the `reporter` so you could write a reporter to get a different behavior.

**Comment by Macadoshis** [comment]
@johnjbarton when I run _$> npm test_ on a bash, and karma.conf.js using _--browsers=Chrome_ (not an embedded phantomjs which might append its console output to the process (bash) stdout) and _logLevel: 'INFO'_, the standard output I'm referring to is the stdout of the bash process right ?
Why then am I supposed to see my `console.debug(..)` outputs on the bash stdout, when I have a dedicated chrome window spawn and open during the test running ? If I understand you right, I should only see my `console.debug(..)` outputs if I F12 my dedicated localhost:9876 chrome window, but not from the stdout of npm test.

**Comment by johnjbarton** [comment]
https://github.com/karma-runner/karma/blob/master/context/karma.js#L116

`console` messages in the browser are forwarded to the server via the 'info' socket call. That ultimately calls the reporter onBrowserLog function.  The reporter does whatever it wants with that result.
